name: document_scanner_example
description: Example app for Document Scanner package - Android only
version: 2.1.1+2
publish_to: 'none'

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Local package dependency
  document_scanner:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true